### ISSUE TITLE
default.yml nor default:<group> get reset

### ISSUE THREAD

**Issue by Orcinuss** [djxy/PermissionManager-2.0#20]
Hello
I am trying to set member as the default group. Every time i restart the server default.yml get reset. I have also tried putting default:true in the member.yml but this has no effect.

When a new player logs in, they still have the group: default-9034cb. They should have the group, member.

### **While server is stopped:**
default.yml
```
groups:
- member
```

member.yml
```
permissions:
- blah.blah
options:
    default: 'true'
    prefix: '&f[&7Member&f]'
    rank: '1000'
default: true
```

default-9034cb.yml
`default:false`

### **After server start:**
default.yml
`null`

member.yml
```
permissions:
- blah.blah
options:
    default: 'true'
    prefix: '&f[&7Member&f]'
    rank: '1000'
default: true
```

default-9034cb.yml
`null`
